version: '2'
services:
    eventos-app:
        image: eventos
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://eventos-mysql:3306/eventos?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8063:8063
    eventos-mysql:
        extends:
            file: mysql.yml
            service: eventos-mysql
